### ISSUE TITLE
Enrollment.csv TimesHomelessPastThreeYears data quality issue causing LSA_Report MonthsHomeless 

### ISSUE THREAD

**Issue by 2008zjqc** [MollyMcEvilley/LSASampleCode#1000]
Hi Molly,
We found there are couple cases in the Enrollment.csv with without TimesHomelessPastThreeYears but MonthsHomelessPastThreeYears have values (i.e. EnrollmentID 190191 and PersonID 91182). In our system, if they don't answer 3.917.4, there won't be able to answer 3.917.5. thus suppose those record with empty value at TimesHomelessPastThreeYears, should have empty value at MonthsHomelessPastThreeYears. Therefore, our result for LSA_Report. MonthsHomeless is different from the sample result. Please let us know how can we handle these situation. 
Thanks.

Best,
Chen

**Comment by MollyMcEvilley** [comment]
The HMIS Data Standards do not define 3.917.5 as a dependent field on the value of 3.917.4.  It should be possible to answer 3.917.5 regardless of the value in 3.917.4.  

I would suggest that you modify your import to set the value of 3.917.4 to 99 in the event that it is NULL so that it is possible to correctly import the value in 3.917.5.
