### ISSUE TITLE
RE Flag 808 for some CoCs

### ISSUE THREAD

**Issue by candiceh214** [MollyMcEvilley/LSASampleCode#1024]
Apologies for not having all the technical speak but I believe I've uncovered an issue with how flag 808 is populating for some CoCs in HDX 2.0.  

Here are two examples from my investigation where we are exporting the correct geography type but it is flagging as an error:
AL-507 project 9448 has a value of 2 in geography type but flags an 808 error saying that the reported type is 3 and expected type is 2.  There is a 2 in their file.

AZ-502 project 46369 has a value of 1 in geography type but flags an 808 error saying that the reported type is 2 and expected type is 1.  There is a 1 in their file.

Can you assist?

**Comment by JulesABrown** [comment]
For AL-507, I think this one may be working correctly, but that the dataset changing between reuploads has gotten things a bit tangled. What I see is that on 11/14, AL-507 uploaded the attached file and got the 808 error. That file does have a 3 in ProjectCoC.csv for 9448. They subsequently reloaded on 11/29 with a new file that shows a 2 for that project ID and isn't getting an 808 error. So at some point they updated the record. The reason the error is still showing up on your report, though, is that the subsequent upload was uploaded as a local file, not an official file. If they want to see the impact on their flags, they need to "replace" their official file so that the file getting the most current flags is an official one.
[alabama_live_lsacsv_84371_2657039490310991379.zip](https://github.com/HMIS/LSASampleCode/files/10179383/alabama_live_lsacsv_84371_2657039490310991379.zip)
![image](https://user-images.githubusercontent.com/44678553/206279234-030e20fd-6370-47d4-a53b-840c9fe95e84.png)

AZ-502 is similar, except that they uploaded on 11/3 for the first time and then haven't reuploaded any reports since then. It looks like their original upload does have a 2 for that project (see attached). I would guess they got the flag, and then they must have gone in to update the record. If they upload a new version of the report, they will no longer see that flag. 
[arizona_live_lsacsv_83307_4097205389858541097.zip](https://github.com/HMIS/LSASampleCode/files/10179440/arizona_live_lsacsv_83307_4097205389858541097.zip)
![image](https://user-images.githubusercontent.com/44678553/206279353-088935ba-eb58-4766-ab66-252c63f0e9a9.png)
