### ISSUE TITLE
Flags 825-1, 827-1

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1026]
Hi @cwanska ,

Flag 825-1 is for RRH project stays. In 2020 year we had a similar flag 822 but for EST project stays and we submitted it for investigation under #650.

Here is a scenario we had at that time:

> We have 5 HoHID&ActiveHHType records in tlsa_HHID table with active enrollments in 2 Projects (Project Types are 1 and 2) where Projects have **the same Geocode** = 129017 **but different address and different GeographyType**.
> Please advise how to solve the issue if:
> - for tlsa_Household.ESTGeography we use GeographyType from the most recent active project stay
> - HoH's have active project stays in 2+ Projects with different GeographyTypes

That ticket was resolved with a comment from you:
> A bug was found in the flag code and has been corrected. The latest flag run on Thursday 1/21 should show resolution of these flags. If the flag still appears, please confirm the geography type isn't misclassified.

Is it possible to check if Flag 825-1 has the same flag code issue as Flag 822 had? And if yes, can it be fixed?

Thank you!
Natalie

**Comment by nataliesus** [comment]
Could you please also look at flag 827-1?

**Comment by JulesABrown** [comment]
I am looking at a download from CA-517 from 11/30 to dig into this flag. I am seeing that it and 827 seem fairly legit. Let me know what you think.

825: _Adult-Child households in RRH (active in residence): There is a large difference in the proportion of households served in urban/suburban/rural areas, as reported in the RRHGeography field of your LSAHousehold file, and the proportion of households served in urban/suburban/rural areas, as reported in your LSACalculated file. Please look to see whether the geography type was misclassified in the LSAHousehold file. (The LSACalculated version of this proportion is derived from the project-level household counts from the LSACalculated file. Each RRH project has a geography type you reported. We summed those project-level counts, among all RRH projects, by geography type to get this proportion. We don't expect the two versions of the proportion to be identical in all cases, but they should be close. This is especially true in this case because you did not report that the unduplicated count of households was lower than the sum of the project-level counts. So one possible reason for the proportions to be different--that the LSACalculated version is double-counting some heads of household--does not apply in this case.)_

LSAHousehold: 

- Sum of RowTotal where HHType = 2 and RRHMoveIn in (1,2) is 28. 
- 6 are in RRHGeography = 1 (21%)
- 22 are in RRHGeography = 2 (79%)

LSACalculated:

- Values where ReportRow = 54 and Population = 0 and HHType = 2 and Cohort = 1 and Universe = 10 for those project IDs that are RRH are: 
![image](https://user-images.githubusercontent.com/44678553/207706332-6743da22-ffca-4a7d-8bbe-e1d61da5c46c.png)

- As you can see, 28 total people were served, consistent with LSAHousehold, suggesting no double counting
- 1 of those projects has a Geography in ProjectCoC.csv of 1, with a count of 1 person served (4%)
- 3 of those projects have a Geography in ProjectCoC.csv of 2, with a count of 27 people served (96%)

I am inclined to concur with the flag that it seems like those distributions should be consistent with each other.

827: 
_Unclassifiable households in RRH (active in residence): There is a large difference in the proportion of households served in urban/suburban/rural areas, as reported in the RRHGeography field of your LSAHousehold file, and the proportion of households served in urban/suburban/rural areas, as reported in your LSACalculated file. Please look to see whether the geography type was misclassified in the LSAHousehold file. (The LSACalculated version of this proportion is derived from the project-level household counts from the LSACalculated file. Each RRH project has a geography type you reported. We summed those project-level counts, among all RRH projects, by geography type to get this proportion. We don't expect the two versions of the proportion to be identical in all cases, but they should be close. This is especially true in this case because you did not report that the unduplicated count of households was lower than the sum of the project-level counts. So one possible reason for the proportions to be different--that the LSACalculated version is double-counting some heads of household--does not apply in this case.)_

LSAHousehold: 

- Sum of RowTotal where HHType = 99 and RRHMoveIn in (1,2) is 1. 
- That HH shows RRHGeography = 1

LSACalculated:

- The value where ReportRow = 54 and Population = 0 and HHType = 99 and Cohort = 1 and Universe = 10 for those project IDs that are RRH results in:
![image](https://user-images.githubusercontent.com/44678553/207709954-192b1cc3-df99-4d8b-9e30-78171dbe2c5e.png)

- That project has a Geography in ProjectCoC.csv of 2

Again, I am inclined to concur with the flag that it seems like the Geography should match up for that household.

**Comment by nataliesus** [comment]
Hi @JulesABrown ,

Thank you for looking it for us! Your explanation gave me a lot of insight.

Here is the most recent test upload: https://hdxsandbox.abtsites.com/dataset/173/warning. Customer changed some data so the numbers are a bit different but we still have Flag 825-1 and Flag 827-1 reported.

### Flag 825-1
![image](https://user-images.githubusercontent.com/28144855/208003582-498400a6-c725-43df-bff2-bdff95fd0abc.png)

HoHID = 2587 is one of those who cause Flag 825-1.

There are 2 records in **tlsa_HHID** table for [HoHID = 2587 && ActiveHHType = 2] in 2 different RRH project stays with **different** Geography Types where Active = 1:
![image](https://user-images.githubusercontent.com/28144855/208013126-8fef4cf2-9932-4091-84af-712ddcdc366d.png)

**Step 6.1**: To insert data into tlsa_Household table, data from tlsa_HHID table where Active = 1 are grouped by [HoHID and ActiveHHType], so these 2 records from tlsa_HHID table are inserted as 1 record into tlsa_Household table. As this time, both RRHMoveIn and RRHGeography are null.

**Step 6.4.1**: RRHMoveIn is calculated only using project enrollment into ProjectID = 77 (GeographyType = 2). ProjectID = 157 (GeographyType = 1) is ignored because MoveInDate is null:
![image](https://user-images.githubusercontent.com/28144855/208008095-d1843250-47f7-43ef-9748-a09d3a213273.png)

**Step 6.5.2**: RRHGeography = GeographyType from the most recent active project stay for [HoHID and ActiveHHType] combination regardless any MoveInDate restriction.
Thus, RRHGeography = 1 because enrollment into ProjectID = 157 is selected as the most recent:
![image](https://user-images.githubusercontent.com/28144855/208000487-619c57b3-e698-49c7-8860-a07f8f744433.png)

**Step 9.3.1** for RowID = 54 and Universe = 10 data from tlsa_HHID table is grouped by several parameters including HHType (ActiveHHType) and ProjectID and inserted into lsa_Calculated table. 
NOTE: only records with AHAR = 1 are used. So only enrollment into ProjectID = 77 is used. Enrollment into ProjectID = 157 is ignored:
![image](https://user-images.githubusercontent.com/28144855/208001133-25b6656f-aa0c-4756-a864-0ca88c3ba969.png)


Thus, we have:
- lsa_Household table:
-- RowTotal = 1
-- RRHGeography = 1 (enrollment into ProjectID = 157 is the most recent)
- lsa_Calculated table:
-- RowTotal = 1
-- ProjectID = 77 (the only one enrollment that has AHAR = 1; GeographyType = 2)

As a result, both lsa_Household and lsa_Calculated tables have RowTotal = 1, but GeographyType is different because enrollments in RRH project with different GeographyType were used for calculations.

I do not think there is an issue in Flag, and there is no issue in sample code. Please advise how customers should reply to this flag.

Thank you!
Natalie

**Comment by nataliesus** [comment]
Hi @JulesABrown ,

Just in case,  Flag 827-1 reported for the identical scenario, but for HHType = 99.

![image](https://user-images.githubusercontent.com/28144855/208219413-cb12f9ca-520a-4ad4-9ef0-fcaed82c79cd.png)

If there is no issue with client's data, sample code, and flag validation rules, could you please advise how Customer should resolve the flag or what explanation should be provided to their liaison.

Thank you!
Natalie

**Comment by JulesABrown** [comment]
I see. Interesting case. Thank you for looking into it. I don't think there are any changes that need to be made, as everything appears to be working as it's supposed to, this is just a strange situation. This flag is only a warning, so these discrepancies are expected very occasionally. I would leave an explanation something like this with the flag: "In LSAHousehold, all enrollments are considered, but only one Geography type can be selected for each project-type grouping. For this file, the specs direct us to choose the most recent enrollment as the basis for assigning Geography. In LSACalculated, ordinarily you might expect both enrollments to show up for Universe 10, at the project level, but in LSACalculated ReportRow 54, we only report on AHAR enrollments ("active in residence," i.e. has a move-in date). In this situation, the household's most-recent enrollment wasn't a AHAR enrollment, so that particular enrollment doesn't show up for ReportRow 54. Their most recent enrollment for LSAHousehold was in one Geography type, but their AHAR enrollment for LSACalculated was in a different Geography type. Both enrollments are legitimate and the Geography types are accurate in each file."
