### ISSUE TITLE
Possible incorrect flag calculation 1231/1233

### ISSUE THREAD

**Issue by jbloescw** [MollyMcEvilley/LSASampleCode#1031]
Can I have someone check to see how a flag is being counted.  I'm looking at the following series:
1231-31
1231-35
1231-36
1233-31
1233-35
1233-36
1233-109
1233-114
1233-187
1233-191
1233-192
1233-265
1233-269
1233-270

To me, it reads as if the flags aren't comparing the same thing.
Flag field one reads as if it is only looking at ES project type = 1
Flag field two is looking at universe 11 which in the code shows it counting both ES types 0 and 1.

I have a couple vendor errors I'm trying to clear and I have a feeling this is why they are getting flagged.

Feel free to reach out to me directly if need be to resolve this.

**Comment by JulesABrown** [comment]
The flag calculation for Flag field one is not based on the HHID.LSAProjecType, but is based on the associated project type for that ProjectID from Project.csv in the LSA upload file. That value encompasses all ES projects, including both tracking methodologies. As an example, for flag 1231-31 in TN-509, when I filter LSACalculated for Population = 1177 and Cohort = 1, I should see a set of rows for Universes 11-16 and then a set of rows for Universe = 10 for each individual ProjectID serving that population. Those ProjectIDs would then get associated with a Project Type from the Project.csv file included in the upload. However, you can see that in the upload file for TN-509, there are only rows for Universes 11-16, and none for Universe = 10. The flag is tripping because there are no project-level counts to roll up.
![image](https://user-images.githubusercontent.com/44678553/224116967-643b488f-5a23-4a26-9c9a-cf8a93219b14.png)

**Comment by MollyMcEvilley** [comment]
Hey Jeff, I am going to close this as an answered question.  If you have follow-up questions or want to set-up a session to talk this through, send Jules an email and he will schedule.
