### ISSUE TITLE
Follow-up for #1011: Dates in 2012 year

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1032]
Hi @MollyMcEvilley ,

Congratulations on a new LSA season!

I have a follow-up question for #1011 about Lookback Date = [ReportStart – 7 years]. Could you please replace the hardcoded 2012 year with 2016 year in 2 places in 01 Temp Reporting and Reference Tables.sql file:

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/ab9b89bf-575d-4196-94aa-d681f6a4dcd7)

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/4f94afaa-db24-4471-8870-ad216026f5bd)

When #1011 can be resolved as well.

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Congratulations to a new LSA season to you, too -- and many thanks for your detailed review of the specs and code!  Your contribution to the accuracy and consistency is invaluable.  

I have some hesitation about dropping those dates because -- especially with changes in the LSA logic from year to year -- I don't want to make it impossible to run an LSA for previous years using the current year's logic.  Does that make sense?

**Comment by MollyMcEvilley** [comment]
Okay, cool -- I'm going to go ahead and close this out.
