### ISSUE TITLE
Step 3.3.2: exit destination codes discrepanly between Sample Code, Spec, Data Dictionary

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1043]
Hi @MollyMcEvilley 

**1.** Could you please compare Spec and Sample Code and update where needed?

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/f6c3e732-8949-491e-86c2-3b5ddf5cb585)

**2.** Could you please take a look if destination = -1 is a valid value?
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/c80fa537-a7cb-4a77-b70c-a0c12f753c9e)

**3.** According to CSV spec, there is no destination = 37. Should it work for LSA as well? If yes, then we need some corrections in the spec. Maybe instead of 37 we should use 24 ("Deceased") because there is no destination 24 in the LSA spec.
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/a0a40ab5-fc9c-405d-bd4b-403e52428d96)

**#4.** `when hx.Destination = 435 then hx.DestinationSubsidyType` - just in case, what if hx.DestinationSubsidyType is null? Should we use 99 instead?

**#5.** LSA spec has exit destination codes that are not listed in https://files.hudexchange.info/resources/documents/HMIS-Data-Dictionary-2024.pdf - I highlighted them. Also, data dictionary has code 435 that is missing in LSA spec. Could you please take a look?
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/e79d6c9a-d3f5-4772-a806-82716acb3c52)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
I've updated the specs, dictionary, and sample code so that destination logic, values, and categories are consistent across all three.

Specs
- Section 3.3 - logic and list of LSA destination categories for setting tlsa_HHID.ExitDest (screenshot below)
- Section 8.11 - Descriptions and logic for ReportRows 101-136

Dictionary
- Lists tab - Updated DestinationLSA list (number 15) 
- LSACalc Values by Row tab - updated report row descriptions for rows 101-136

Sample Code
- 3.3.2
- 8.11

![image](https://github.com/HMIS/LSASampleCode/assets/6156815/8e8c2e81-375b-436c-9120-c8bcabb258d3)
