### ISSUE TITLE
Spec Section 4: Project.OperatingEndDate >= ReportStart or Project.OperatingEndDate is NULL

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1049]
Hi @MollyMcEvilley ,

There is `Project.OperatingEndDate >= ReportStart or Project.OperatingEndDate is NULL` condition in the Spec for next sections:
- 4.3. Get Funder.csv Records / lsa_Funder 
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/dfcdbeb5-fb20-4b74-ac5f-4b612c383920)
- 4.5. Get Inventory.csv Records / lsa_Inventory
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/b3026a09-fc46-45fc-a20b-3553e14075f1)
- 4.6. Get HMISParticipation.csv Records / lsa_HMISParticipation
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/6e3ba957-8429-49e1-92a8-e60919dfcb94)
- 4.7. Get Affiliation.csv Records / lsa_Affiliation 
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/d6d3acde-1a77-4315-84cc-dfdc79bfcd63)

But there is no `Project.OperatingEndDate >= ReportStart or Project.OperatingEndDate is NULL` condition in the Sample Code so it is possible to have data in lsa_Funder, lsa_Inventory, lsa_HMISParticipation, and lsa_Affiliation tables for Programs where OperatingEndDate >= LookbackDate and OperatingEndDate < ReportStart.

Could you please take a look?

---

In case  `Project.OperatingEndDate >= ReportStart or Project.OperatingEndDate is NULL` condition should be added, then "For all Project IDs in Project.csv" text should be corrected in LSA Data Dictionary FY2023.xlsx :
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/62f66b6d-7713-401a-81ef-6b44c05083c7)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
**Funder** and **Inventory** - The expectation is that -- because the HMIS Data Standards require that projects have funding and inventory data -- there will be at least one active record for each active project.  The "There must be at least one..." note is a statement of that expectation.  It isn't a selection criteria, though -- if there are active records for inactive projects, the HDX flags will catch it and CoCs will have the opportunity to correct that.  In the Dictionary, the "active during the report period" applies to the Funder/Inventory records; that's consistent with the logic, so I'm leaving those descriptions alone.

**HMISParticipation** - Operating dates _are_ a selection criteria because we are looking for a complete history and not just active records -- but only for active projects.  

**Affiliation** - We only need this for active projects and there is no date range associated with Affiliation, so operating dates are part of the selection criteria for these records.

I am updating the language in the Dictionary to clarify that HMISParticipation and Affiliation are required only for projects active during the report period.  (Commit forthcoming.)

![image](https://github.com/HMIS/LSASampleCode/assets/6156815/247d2af0-58eb-4820-a494-6c85383b9e36)
