### ISSUE TITLE
ReportRow 901-902, 905-908: consistency between Sample Code and Spec

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1126]
Hi @MollyMcEvilley ,

Can we update Sample Code to use the same Project Type conditions for consistency for ReportRow = 901-902 and 905-908?

After resolving #1124 and #1125, Spec will use the identical `ProjectID = lsa_Project.ProjectID and ProjectType is not in (9,10);` condition:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/011e23ed-a99d-40ea-83c5-7fc40c0eee2e)

In Sample Code we have:
- for ReportRow 901-902: p.ProjectType in (1,2,3,8,13) (we have a separate ticket to add ProjectType = 0 #1124 )
- for ReportRow 905: p.ProjectType not in (9,10)
- for ReportRow 906: no ProjectType at all
- for ReportRow 907: p.ProjectType in (0,1,2,3,8,13) 
- for ReportRow 908: p.ProjectType in (0,1,2,3,8,13) 

Maybe we can use p.ProjectType not in (9,10) in Sample Code and it will match the Spec? What do you think?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
For 901 and 902, we don't need the ProjectType criteria at all because we're counting enrollments in tlsa_Enrollment (which are already limited by project type), so I am updating the specs as follows (and removing the criteria from the sample code):
![image](https://github.com/HMIS/LSASampleCode/assets/6156815/723a98df-5b9d-40dd-abba-0f2c7765bc32)
The same is true for 906:
![image](https://github.com/HMIS/LSASampleCode/assets/6156815/598afd4d-d0dc-4a30-80bc-eaf78c5f7e74)
I've updated the sample code for 907 and 908 so that it is consistent with the specs and uses _ProjectType not in (9,10)_ instead of _ProjectType in (0,1,2,3,8,13)_
![image](https://github.com/HMIS/LSASampleCode/assets/6156815/f63a81d8-ef04-40e4-889e-1d3de2c7630c)
