### ISSUE TITLE
Label on LSASampleCode page

### ISSUE THREAD

**Issue by MichelleNevius** [MollyMcEvilley/LSASampleCode#1138]
The annotated specs-- the ones from July 2023-- have a title/link of "[EnrollmentCoC for NotOneHoH Count](https://github.com/HMIS/LSASampleCode/commit/54d027f70416d7c564205f6227f8f5200e8df59d)". I can still open that up and
 download the annotated specs, but something seems wrong with the [listing.] Can you take a look, please? Thanks!

![LSASampleCode label for annotated specs](https://github.com/HMIS/LSASampleCode/assets/64848927/b6dfeb7d-f1cb-48a7-8182-36ab927a2534)

**Comment by eanders** [comment]
The second column on the code page just lists the the "commit message" from the last commit that touched the file in the first column.  In this case, because "LSA Programming Specifications FY2023 - Annotated.docx" is a binary file, any change to it will update the entire file.  You can click that label to see what was changed in that particular commit, but again, because the file is a "binary" file, that's not super useful in this case.
