### ISSUE TITLE
Sample Code, Spec Section 5.4: DisabilityStatus no longer uses logic based on [HIV], [SMI], and [SUD]

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1143]
Hi @MollyMcEvilley ,

[HIV], [SMI], and [SUD] have been removed from DisabilityStatus recently in Sample Code:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/c25cb1ea-cdfb-4a1f-bd4c-65b127093fdd)

Could you please remove this logic from the FY2023 changes?
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/53b690c8-a028-4a56-bbe7-31a64e9565f9)

And please remove the correspondent logic from Spec (section 5.4):
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/fd83ab25-254c-47ce-8754-e7f51e2e1277)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you!  I should have replaced that step in the code when I moved the code for setting HIV/SMI/SUD (which i did because it made a massive difference in speed).  I'm adding this to the end of section 5.4 of the code.

![image](https://github.com/HMIS/LSASampleCode/assets/6156815/8ff03339-ec85-4f89-b1c1-995451c6e18f)
