### ISSUE TITLE
HDX Upload: rejected

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1169]
Hi @MollyMcEvilley , @JulesABrown ,

Could you please advise what flags are used to reject upload? I.e. https://hdxsandbox.abtsites.com/module/lsa/uploads/297 was rejected because of data entry issues in LSAHousehold.csv:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/fc2fc74e-483d-4660-b443-7b3375e1d869)

Because the upload itself was rejected, there was no way to get the full flags list we should work on.

Thank you!
Natalie

**Comment by JulesABrown** [comment]
This upload was rejected because in row 10544, the LSAHousehold file has a value of 27 in the ESTLivingSit column and a value of 3 in RRHDestination. Per the data dictionary, those are not allowable values for those columns. Once those values are corrected in the output, the file will be accepted and the data errors/warnings will become visible. Note, though, that during this testing window, not all data errors/warnings are finalized, per my email.
