### ISSUE TITLE
Possible issue in 7.5 of Sample SQL

### ISSUE THREAD

**Issue by evaripatis** [MollyMcEvilley/LSASampleCode#1191]
I'm concerned there may be an issue in step 7.5 of the Sample SQL., as it appears to be leaving out records from ch_Exclude.  For example, as far as I can tell, it looks like PersonalID 411055 should have records inn ch_Exclude spanning from 6/23/2021 (their EntryDate in the 816388 Enrollment, which has LSAProjectType of 2) through 12/16/2021 (their latest, and only, LastActive value from tlsa_ExitHoHAdult).  They have a second Enrollment (815075), which is LSAProjectType of 13 and it is missing MoveInDate.  Is it possible that this is causing the Sample SQL to erroneously keep those other record values from getting into ch_Exclude?  Or am I misinterpreting something and they really shouldn't be included?  If the latter, I would greatly appreciate some clarification.  Thank you.

**Comment by MollyMcEvilley** [comment]
I believe that this issue was caused because the temp tables I posted here were based on a set of sample HMIS data that I should also have posted but didn't.  (In the updated version of the sample data, the TH enrollment doesn't exist.) 

I apologize for the time-consuming oversight.  I posted the sample HMIS data and updated LSA/temp table output; I'm closing this now, but please feel free to re-open if you are still seeing issues.
