### ISSUE TITLE
Erroneous Logic Removal from Step 4.1?

### ISSUE THREAD

**Issue by evaripatis** [MollyMcEvilley/LSASampleCode#1224]
The "04_01 Get Project Records.sql" file states that there were no changes, but it appears that some date logic was removed (see diff screenshot, below).  The specifications document appears to confirm that there should have been no changes made.  Was the "rpt.ReportEnd >= hp.OperatingStartDate" logic removed in error?

![image](https://github.com/user-attachments/assets/7611871b-8e30-4ec3-9355-ecdd358fde85)

**Comment by MollyMcEvilley** [comment]
It was not removed in error -- the commit for that change was posted in April to address #1218. 

- The specs do not limit the PDDE data to projects that start prior to ReportEnd, which was intentional.
- The sample code was joining on OperatingStartDate, which was a bug.  

![image](https://github.com/user-attachments/assets/b29f4445-c08a-46d8-affd-884383f2ddda)
