### ISSUE TITLE
LSA Data Dictionary FY2024.xlsx -> Files: File ID numeration

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1227]
Hi @MollyMcEvilley ,

Just want to confirm the gap in the numeration is intentional.

![image](https://github.com/user-attachments/assets/5882f2fe-841d-4fbc-935e-a10dfcc50f21)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
I have tables in my fake HMIS database that include all of the HMIS CSV and LSA files, columns, and option lists.  I created them when I started working on the LSA structure in 2016 and added the HMIS files later.  I don't remember if it was intentional from the beginning that the ID numbers for the LSA files are single-digit and the HMIS files are double-digit, but 6,7,8, and 9 are not missing from the dictionary -- they just don't exist in my database.  I kind of wish I could renumber them -- I'd start with the HMIS files first -- but it would break some things in the HDX.
