### ISSUE TITLE
Spec: Section 2.3: question about Lookback Date for HIC

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1232]
Hi @MollyMcEvilley ,

Spec provides info for Lookback Date for **LSA purposes**:
![image](https://github.com/user-attachments/assets/2a990898-aab4-46bb-9525-87a750c776cb)

What about HIC? Should the Lookback Date still be [ReportStart – 7 years]?

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
The LSA is still the LSA, even if the scope is HIC... all of the logic applies unless otherwise specified.  I think the SPMs still use a fixed lookback date of 10/1/2012, and I wrote "For LSA purposes..." when we switched to a rolling lookback.

(Now that you point it out, however, "For LSA purposes" is redundant in a 175-page document specifically devoted to the LSA, and I am removing it -- it will be in the next commit.)
