### ISSUE TITLE
Sample Code (Step 3.3.1): hmis_HMISParticipation  restrictions for hmis_Services 

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1240]
Hi @MollyMcEvilley ,

In the Spec (EntryDate instructions) it is said:
_If an enrollment encompasses more than one period of HMIS participation, **the most recent record of HMIS participation is used** to adjust enrollment dates._ 
![image](https://github.com/user-attachments/assets/1faf6006-106a-4840-8950-9c69b89bf1a0)

1. I wonder if "the most recent record of HMIS participation is used" rule should be applied for hmis_Services. Because now for `FirstBednight` and  `LastBednight` different HMIS participation records can be used.

2. Could you please confirm that BedNight on HMISParticipationStatusEndDate should always be ignored (because of `svc.DateProvided < part.HMISParticipationStatusEndDate` condition)?
![image](https://github.com/user-attachments/assets/52e93427-3705-46ec-8dc2-8d6417937319)

I am asking because i.e. for ExitDate = HMISParticipationStatusEndDate which is <= ReportEndDate is valid:
![image](https://github.com/user-attachments/assets/20c21ccb-6f02-40de-9a5d-852d4c99014e)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
1. The short answer is yes -- the bed night dates should be limited to the most recent period of HMIS participation.
2. Yes, bed nights on HMISParticipationStatusEndDate should be ignored, as should bed nights on OperatingEndDate.

I have re-written the sample code for 3.3.1 to take that into account and uploaded the changes.  I am leaving this open because I'm working my way through all of the date comparisons in the specs and sample code and don't want to close the issue until all of the corrections are complete and uploaded.

![image](https://github.com/user-attachments/assets/0669e714-48a3-400e-b78e-ae4e710c0dbd)

**Comment by MollyMcEvilley** [comment]
See Issue #1272 for further detail.
