### ISSUE TITLE
Steps where hmis_HMISParticipation restrictions are not applied to hmis_Services (both Spec and Sample Code)

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1243]
Hi @MollyMcEvilley ,

We use hmis_HMISParticipation restrictions on hmis_Services  dates in the 3.3.1 step:

![image](https://github.com/user-attachments/assets/ad1c2cc8-ac76-4309-97a5-7a72c5828349)

hmis_Services table is used in a few more steps in the LSA report:
- 3.4.2
- 5.8.2
- 6.12.2.b
- 6.13.2
- 7.6.2
- 7.11.2.b
- 9.2.2
- 9.5.1
- 9.5.3
- 9.5.5
- 10.3

I wonder if hmis_HMISParticipation restrictions should be applied there as well.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
3.4.2 - The HMIS Participation restrictions are not needed when inserting tlsa_Enrollment records because the span of the record in tlsa_Enrollment is limited to tlsa_HHID.EntryDate-->tlsa_HHID.ExitDate or ReportEnd, which is adjusted if necessary so that it doesn't extend into period of non-participation.  
5.8.2 - The tlsa_Enrollment records are limited to the period of HMIS participation and the bed night dates have to occur in the timeframe of the enrollment, so additional checks are not necessary
6.12.2.b - Bed nights have to occur during the period of the enrollment defined in tlsa_HHID, which is limited to periods of HMIS participation, so no need for additional checks.
6.13.2 - Same as 6.12.2.b
7.6.2 - Also covered by limiting bed nights to the span of the enrollment as adjusted in tlsa_Enrollment to exclude periods of non-participation
7.11.2.b - Limited by tlsa_HHID dates.
9.2.2 - Limited by tlsa_Enrollment dates.
9.5.1 - Limited by tlsa_Enrollment dates
9.5.3 - Limited by tlsa_Enrollment dates
9.5.5 - Limited by tlsa_Enrollment dates
10.3 - This is a data quality count, so we don't want to limit it to periods of participation.
