### ISSUE TITLE
Likely issue with changes to Step 10.5

### ISSUE THREAD

**Issue by evaripatis** [MollyMcEvilley/LSASampleCode#1276]
It looks like there is a contradiction in the changes for Step 10.5.  The left join has logic for ExitDate <= ReportEnd (highlighted green), but the where statement has ExitDate >= ReportEnd (highlighted yellow).  If the left join on hmis_Exit has us only including dates on, or prior to, the report end date, then it would be impossible to find any exits _after_ the report end date.  Presumably one of these is incorrect.  Assuming I am correct, and one of these is corrected, wouldn't the logic highlighted in yellow be duplicative and unnecessary.  Even if it is not, parentheses would be required around it, following the and.
![image](https://github.com/user-attachments/assets/e2aef2c0-0b92-4d22-a9a6-fa717a3a3795)

**Comment by nataliesus** [comment]
Hi @evaripatis and @MollyMcEvilley ,

I just want to say that:
1. brackets should be used around `x.ExitDate is null or x.ExitDate >= ReportEnd`.
2. instead of `x.ExitDate >= ReportEnd` we need `x.ExitDate >= ReportStart`
3. do we need any date restrictions for HoH project stay here? I.e. that HoH dates cover the project stay dates? Or/and HMISStart/HMISEnd dates restrictions similar to those that were applied to `n` enrollments?
4. Do we need a restriction that if x.ExitDate is not null, then x.ExitDate must be greater than n.EntryDate?

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
I am replacing "x.ExitDate is null or x.ExitDate >= ReportEnd" with "(x.ExitDate is null or x.ExitDate >= ReportStart)".

We don't need any additional restrictions on the HoH entry/exit dates or anything else that might prevent us from identifying enrollments that are, in whole or in part, outside of the period of HMIS participation.
