### ISSUE TITLE
Sample HMIS Data.zip: HealthAndDV.csv: missing rows for EnrollmentIDs

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1285]
Hi @MollyMcEvilley ,

The next EnrollmentIDs don't have record(s) in HealthAndDV.csv file:

- NBN10528644
- NXS10212178
- NXS10220455
- NXS11328642
- PSH14828649
- RRH13228643
- RRH14110376
- RRH14110377
- RRH15828648
- TRN10428650

Could you please take a look if it was done intentionally?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Not intentional but I didn't see it as a problem.  Adding records in case it's problematic and because I'm making a bunch of other changes today as well.  

From here on out, I am only going to change things in the sample data if:
- There is an issue that prevents import.
- Something in the data (probably PDDE-related) is triggering a lot of flags in the HDX when the LSA is uploaded.
