### ISSUE TITLE
Section 3.3.1: Effective Move-In Date issue

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1317]
Hi @MollyMcEvilley ,

**Issue 1.** `MoveInDate is null` condition exists in the Sample Code, but is missing in the Spec. Thus, according to the Spec, if MoveInDate is null, then the Effective Move-In Date will be either HMISStart or HMISStart 

**Issue 2.** The Spec uses `MoveInDate < EntryDate` condition. Could you please specify:
- if the effective EntryDate should be used (in this case, EntryDate should be bold in the Spec, and Sample Code should be fixed)
- if the raw EntryDate should be used (in this case. please replace `EntryDate` with `Enrollment.EntryDate` is the Spec)

![image](https://github.com/user-attachments/assets/361bb3b5-ed62-412d-b365-4833ee2d9ee2)

![image](https://github.com/user-attachments/assets/f1399988-3f47-45b8-a314-18817166826e)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Adding the _MoveInDate_ is null criterion to the specs...

The intent is to reference the unadjusted HMIS _EntryDate_ -- we disregard the _MoveInDate_ if it is earlier than the _EntryDate_, but otherwise, the adjustments for operating and HMIS participation dates are also applied to the _MoveInDate_.
