### ISSUE TITLE
Household Makeup Question

### ISSUE THREAD

**Issue by eanders** [MollyMcEvilley/LSASampleCode#1381]
We're seeing flag `969-1.28` 
> Adult-Child households: You reported that zero people were served (active in residence) during the entire report period in this HMIS-participating project, `project name`. Please confirm if this is correct and explain any reasons why no people in this household type were served.

in situations where a household is made up of adults and children, but the children all have a `RelationshipToHoH` of `99`.  The adult has `RelationshipToHoH` of `1`.  

In step **3.4.1** data from `hmis_Enrollment` is only included if `and hn.RelationshipToHoH in (1,2,3,4,5)`.  If you can determine that a household contains adults and children based on the ages of the household members, is there a reason we're excluding enrollments where the relationship wasn't collected?  

The CSV specification and the dictionary seem to disagree about what values should be allowed.
<img width="826" alt="Screenshot 2024-12-12 at 3 30 21 PM" src="https://github.com/user-attachments/assets/1ddaddd6-c313-465e-adea-cd83b9556643" />
<img width="1105" alt="Screenshot 2024-12-12 at 3 30 41 PM" src="https://github.com/user-attachments/assets/5dcaa937-3f1f-4a08-a169-e70304c68097" />

There isn't an `Client doesn’t know` or `Client prefers not to answer` option for relationship, so my theory is that people are choosing `Data not collected`.  

We could implement a data fix to shift all 99 to 5, but I wonder if that's necessary given that the household type can be determined from the ages of the clients.

**Comment by MollyMcEvilley** [comment]
The HMIS Data Dictionary doesn't allow for anything other than 1-5 for _RelationshipToHoH_.  Other fields allow for _Client doesn’t know/Client prefers not to answer/Data not collected_ responses, but this one does not.  That's not an accident or an oversight -- those values are not in the HMIS Data Standards because the intention is that users MUST select a value between 1 and 5 and that an HMIS should enforce that.  It's a simple enough thing to add to a web form, but some systems -- even at this point -- don't enforce it.  As such, I added 99 to the HMIS CSV specs to facilitate data exchange because the consensus among vendors at the time (2014) was that they wanted to be able to import/export data that included invalid values -- but that _doesn't_ make it a valid HMIS value that a user should be able to select.  

In order for the enrollments to be included in the LSA, the value in RelationshipToHoH has to be between 1 and 5.  The intention there is that CoCs should fix the underlying issue and not that missing values should be changed to 5.

**Comment by eanders** [comment]
Thanks for the background @MollyMcEvilley !  Our work-around is exactly as you described 99 -> 5, which seems to have fixed the flags.
