### ISSUE TITLE
HUD CSV Export sample data: Children-only Households

### ISSUE THREAD

**Issue by kiadso** [MollyMcEvilley/LSASampleCode#685]
Hi @bdavis-pcl 

I think this is the last one I have for the day, lol, thanks for your patience with these. 

When I query against Client.csv and Enrollment.csv, I find 197 children-only households, where the head of household is under 12. That is excluding any that showed up in the RHY or YHDP projects (even though those probably shouldn't have under-12 humans as hohs either.)

Some examples are:

- PersonalID 62247, HouseholdID 169304
- PersonalID 73378, HouseholdIDs 177022, 177023, 177024 (and more)
- PersonalID 73819, HouseholdIDs 177742, 177743

Children-only households affect reporting, they generally get classified as Unknown Household Type which can throw counts and such. If they were added intentionally as wild test data, that's fine, but wanted to point it out.

Thanks!

**Comment by bdavis-pcl** [comment]
Hi @kiadso,

I'll be working my way through these today, and send my comments on them. This is just to let you know I've received them all and am investigating them to see if changes are needed.

Thanks for sending such detailed reports,
Bryan

**Comment by bdavis-pcl** [comment]
I know a number of these child only households are intentional. Since they don't really affect testing, I don't see a need to change them. If they are causing issues with uploading the HMIS CSV that are preventing testing I'd be happy to revisit this issue then.

Closing this issue since I see no need for action at this time.
