### ISSUE TITLE
9.3: Spec issues

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#723]
Hi @MollyMcEvilley ,

**1.** It is a typo in "EntryDate**t**"

**2.** Source -> tlsa_Enrollment refers to:
- ProjectType
- TrackingMethod
that are no longer columns in tlsa_Enrollment table
![image](https://user-images.githubusercontent.com/28144855/137298253-cc6e245f-723c-4c15-b570-7fed1a6aa9a3.png)

**3.** Could you please take a look if "ProjectType = 13 and ExitDate = CohortStart and MoveInDate = CohortStart" is still actual? 
![image](https://user-images.githubusercontent.com/28144855/137298793-c84d5376-4fe6-49b9-ac33-a1d665ada439.png)

**4.** Now it looks like "ExitDate is NULL, or ExitDate > CohortStart; or" relates to "If ProjectType=1 and TrackingMethod = 3, there is a BedNightDate on CohortStart;".Maybe it should be shifted to the left?
![image](https://user-images.githubusercontent.com/28144855/137299048-84d2b16c-7111-4d15-a022-dd797586f72d.png)

**5.** [lsa_Calculated -> Value] describes value for row 53 ("Count of distinct PersonalIDs in tlsa_Enrollment"). Shouldn't it be updated somehow to include what is actually counted for row 54 ("Distinct combinations of HoHID/ActiveHHType in tlsa_HHID")?

![image](https://user-images.githubusercontent.com/28144855/137305140-c50e6253-a467-4156-abbf-2003731c8d84.png)

**6.** Please fix ProjectType for Universe = 15:
![image](https://user-images.githubusercontent.com/28144855/137306994-ef4e2db5-8f97-44e7-b915-d8170275bd45.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
1. Fixed -- commit forthcoming -- and please let me take this opportunity to thank you for your wonderfully detailed issues.  I am so very grateful that you are a part of this group. 
2. I need to go through the specs and incorporate the **LSAProjectType** instead of using HMIS _ProjectType_/_TrackingMethod_.  
3. You are (of course) correct.
![image](https://user-images.githubusercontent.com/6156815/137350227-0e97d6fe-52d6-4133-abef-f0e02d157ffa.png)
4. (See 3.)
5. **(Leaving this issue open to respond to this later.)**
6. Fixed -- thank you.

**Comment by MollyMcEvilley** [comment]
5.  Yes!
![image](https://user-images.githubusercontent.com/6156815/137351736-8e7a23f8-df4c-4ba0-be00-b27463c6a69f.png)
![image](https://user-images.githubusercontent.com/6156815/137351818-1db0f80f-4289-44b2-a05d-3ffda7dcc43e.png)
