### ISSUE TITLE
Step 7.6: Sample Code issue with earliest CHStart and latest LastActive

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#785]
Hi @MollyMcEvilley , @kiadso 

In the spec Section 7.6 earliest CHStart and latest LastActive are used:

![image](https://user-images.githubusercontent.com/28144855/139274508-32979abc-0e90-408f-b97f-8a89836e5419.png)

But Sample Code doesn't have **earliest** CHStart and **latest** LastActive logic. Could you please take a look?

Also, I wonder why in Spec - Enrollment in Entry/Exit ES or SH - `[LastActive + 1 day]` is used and not `[latest LastActive + 1 day]`.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Sample code corrections to 7.6.2 and 7.6.3 to use earliest **CHStart** and latest **LastActive**.
![image](https://user-images.githubusercontent.com/6156815/139947494-812f0f5f-6865-4865-80dc-7a0529833825.png)

Spec correction for the section on Enrollment in Entry/Exit ES or SH (because there will not be any NULL **ExitDate**s for enrollments relevant to CH for the exit cohorts...
![image](https://user-images.githubusercontent.com/6156815/139946798-52941879-f7cd-4306-89e4-2c83f3fba9c2.png)
