### ISSUE TITLE
Section 7.8: empty rows in the Spec

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#793]
Hi @kiadso ,

Do you also see these empty rows?

![image](https://user-images.githubusercontent.com/28144855/139440761-bea64659-8bac-421e-9ae6-d23d5cc5d72c.png)

![image](https://user-images.githubusercontent.com/28144855/139440715-203a5b2c-e085-47bb-bab6-6fe55e737f2c.png)

**Comment by kiadso** [comment]
It's all track-changes related, where the text was deleted, and not the rows. It will be fixed in the final version. Thanks!

**Comment by nataliesus** [comment]
Hi @kiadso ,

When is it expected for the final version to be released?
This ticket was closed but there are still empty rows in the tables.
![image](https://user-images.githubusercontent.com/28144855/140044569-b8116bbb-daa7-4a12-a829-277679e477c7.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Hi @nataliesus... I'm sorry -- I closed the ticket because I didn't see the empty rows in the specs document... If I set Word to view simple markup or no markup on the Review tab, I see this:
![image](https://user-images.githubusercontent.com/6156815/140082780-1008e9d3-c36e-48fe-8619-3baf77d60cb1.png)
If I set it to view all markup, I see this:
![image](https://user-images.githubusercontent.com/6156815/140083100-4b85c063-87b6-4414-8e2e-f260e8f5433a.png)
I wonder if this is a Word issue?
