### ISSUE TITLE
Section 7.8 - discrepancy between Sample Code and Spec

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#794]
Hi @MollyMcEvilley , @kiadso ,

**1.**
Sample Code (step 7.8.1) uses `chep.episodeDays >= 365` that is not in the spec.

**Sample Code**
![image](https://user-images.githubusercontent.com/28144855/139443065-3cb38b80-2210-4200-99b7-7c473f984a1b.png)

**Spec**
![image](https://user-images.githubusercontent.com/28144855/139443950-d8d72d34-5d6f-49bc-9bc2-121cfdd68bc3.png)

Maybe `episodeDays >= 365` was a copy/paste from step 5.10.2?
![image](https://user-images.githubusercontent.com/28144855/139654602-ef0a8e65-7504-4761-8e92-35c79ab3a8b1.png)

**2.**
Spec has logic for `CHTimeStatus = -1` but I cannot find it in Sample Code.
![image](https://user-images.githubusercontent.com/28144855/139445335-06683183-39ef-4029-92c7-a45f198ef8e5.png)

**3.** Sample Code (step 7.8.2) has cohort logic. But there is no cohort logic in the Spec.
![image](https://user-images.githubusercontent.com/28144855/139657645-ba79ac8d-920f-4dea-8601-d5bd769dbf14.png)

**4.** Spec has CHStart logic that is missing in Sample Code.
![image](https://user-images.githubusercontent.com/28144855/139657567-94a17385-1ff0-4d6c-b0b8-75d18a6f1923.png)

I wonder or step 7.8.2 can be reworked to be similar to step 5.10.3?

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
1.  Updating 7.8.1 in the sample code -- **episodeDays** >= 365 is redundant to **episodeStart** being at least one year prior to **episodeEnd**.
2. Updating the specs -- **CHTimeStatus** = -1 when **CHTime** = 270 is n/a for tlsa_Exit.
3. No change... **Cohort** is used in the sample code because of the way that the subquery is structured -- it is used to ensure that only the relevant tlsa_ExitHoHAdult record is updated in the event that there are more than one for a given person -- but it's not needed in the specs description, which already references the **CHStart** and **LastActiveDates**.  (I could have joined on those instead, I suppose, but it doesn't ultimately matter.)  
4. Correcting 7.8.2 in the sample code.  
(In 5.10.3, we can just use ch_Episodes.**episodeDays** for the total number of days because we're working with a single **CHStart**-**LastActive** timeframe for each person.  We can't use that approach here, where we might have multiple timeframes for any given person (because a person can appear in multiple cohorts and have multiple CHStart-LastActive date ranges), because it's possible that a single episode could include dates that ARE relevant (for example) for a person when s/he appears in Cohort -2, but aren't relevant when s/he appears in Cohort 0.)
![image](https://user-images.githubusercontent.com/6156815/139942354-96298cb3-8aa3-4223-90d0-e6e8738ccadc.png)
![image](https://user-images.githubusercontent.com/6156815/139941998-3461ece9-df73-4478-a49f-dd222b2736b4.png)

NOTE:  There are also a few references to **LastInactive** in the specs that I am correcting to **LastActive** -- **LastInactive** is not relevant to chronic homelessness.
