### ISSUE TITLE
dateadd() has different first input parameter working with years

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#807]
Hi @MollyMcEvilley .

I've just noticed that Sample Code has both "dateadd(**yy**,..)" and "dateadd(**yyyy**,..)":

![image](https://user-images.githubusercontent.com/28144855/140533963-1800da47-d37b-406f-b052-41cbea82b4ba.png)

Just want to confirm both ways work correctly for you. If not - there are many places to review and update to be consistent within the whole project.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Is this a problem for anyone?  SQL Server doesn't seem to care whether the parameter is 'year', 'yy', or 'yyyy.'  I think that the built-in functions in other DBs have different names (e.g., 'DATE_ADD' in MySQL), so altering the parameter wouldn't improve anything in terms of cross-system compatibility -- but if it matters to anyone, I'll update all of the DATEADD() parameters so that they're consistent.  

(If it matters to you, please let me know your preferred parameter.  Also, if anyone is familiar with a system-agnostic way to manipulate dates like this, I'd love to hear about it.)

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

In MySQL I use DATE_ADD/DATE_SUB so the year format in Sample Code is not a problem for me at all. 

You can close this ticket. Thank you!
