### ISSUE TITLE
Step 8.3.1: question about HHType = null

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#825]
Hi @MollyMcEvilley ,

tlsa_AveragePops table has HHType = null for scenario from Step 8.3.1:
![image](https://user-images.githubusercontent.com/28144855/142435854-dc8836b8-e0d1-404b-b8a4-400512b9f06b.png)

Just want to confirm that HHType = null should be excluded on Step 8.3.38 because of `p1.HHType = p2.HHType` (in MySQL null=null is never true)?
![image](https://user-images.githubusercontent.com/28144855/142436274-0cf33c1c-fdc2-40e4-baac-609cf87b4ec1.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Confirmed!  Rather than inserting absolutely everyone to tlsa_Pops for population 0, the counts for sections 8.4 - 8.11 join to tlsa_AveragePops on EITHER **PopID** = 0 OR matching **HoHID** and **HHType**.

For LSAHousehold counts:
![image](https://user-images.githubusercontent.com/6156815/142446393-a0573857-35d8-48cb-9a92-674d53a25b7e.png)

For LSAExit counts:
![image](https://user-images.githubusercontent.com/6156815/142446611-a171a7cb-eece-445f-8a03-c4bc39407018.png)

OH!  Actually, there's a bug in the screenshot above for LSAExit counts -- the join to tlsa_AveragePops should always require that ex.Cohort = pop.Cohort and not only for populations other than 0.  Correction / commit forthcoming.

![image](https://user-images.githubusercontent.com/6156815/142447827-e32be6e0-859d-4322-bc67-d1bbc92b9406.png)
