### ISSUE TITLE
Flag 851 & 852 (Exit Date vs bednight)

### ISSUE THREAD

**Issue by MollyMcEvilley** [MollyMcEvilley/LSASampleCode#862]
![image](https://user-images.githubusercontent.com/6156815/144668515-90423e91-c70a-4d94-a7e8-e6c05dc39170.png)
"The number of people with this issue was significant."  Is there a threshold on this?  There were only 2 -- a minor and self-explanatory DQ issue identified as a data error / vendor issue.

**Comment by kiadso** [comment]
Hi Molly,

Jules provided this as to why it is a vendor issue and not an HMIS Lead issue:

> 
> It’s looking for exit dates that differ from last bed night + 1. Fixing that for LSA is in the specs, so it’s a vendor issue. The vendor could go back to the CoC, I suppose, but they’re expected to program around it from our perspective.
> 
> **For night-by-night ES enrollments, any ExitDate must be one day after the last recorded bed night.** For any exit where there is not a record of a bed night for the preceding date:
> 
> ·         LSA reporting procedures will use an effective exit date of [last bed night + 1 day].
> 
> ·         Destination will be reported as unknown, if applicable.

Feel free to re-open if there is more context needed!

Thanks!

**Comment by MollyMcEvilley** [comment]
The DQ counts aren't looking at effective exit dates -- they're looking at actual HMIS exit dates to get a sense of how many were 'adjusted' for LSA purposes -- so this isn't a vendor issue.

**Comment by MollyMcEvilley** [comment]
(This is why the DQ universe is different from the LSAPerson/Household/Exit universe -- it's looking for the lumps that may have been smoothed over by the reporting procedures.)

**Comment by JulesABrown** [comment]
Makes sense - sorry about that!

**Comment by nataliesus** [comment]
So what is decided to do with this flag? Is it still an issue that Customers should fix?

Please notice flag 851-1 is similar to Flag 852-1 but with an exception that HMIS exit date is empty.

**Comment by nataliesus** [comment]
Hi Genelle,

Just in case, we still have this flag reported.

**Comment by kiadso** [comment]
We are working on this one, I'll update when we know more. Thanks Natalie!

**Comment by cywiseman** [comment]
Is there any update on the status of this set of flags?

**Comment by kiadso** [comment]
Hi everyone,

This set of flags happens when there is a bed night beyond the ExitDate. The LSA logic smooths out this issue by pushing out the ExitDate to one day beyond the last bed night, and giving it a missing Destination, since the Destination in HMIS would only apply to the ExitDate it was associated with. The effect of this on LSA data quality is that if there are many records like this, it will cause a higher incidence of missing Destinations than a community is expecting. These flags are meant to prompt communities to correct the data issues where those Destinations are now missing.

We did decide to make this a Warning with a threshold of 5. Once this is implemented, I'll update here! Thanks for your patience!

**Comment by kiadso** [comment]
This fix has been pushed to production. Please re-open if you are still seeing these. Thanks everyone!
