### ISSUE TITLE
Question: can multiple rows of the same flag be gathered into 1 flag row?

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#865]
Hi @kiadso ,

Here is our testing on DB with much more info: https://testing.hudhdx2.info/dataset/1314/warning

Flag 519-1 is reported 2,252 times. So the flag is reported **for each LSAHousehold row** what doesn't match the expected condition.

I just wonder if it is possible to report flag per unique condition, and have a list of row numbers in "Observation Number (not counting the header row) in your LSAHousehold file" instead of report each row as a separate flag?
![image](https://user-images.githubusercontent.com/28144855/144851727-24d85f86-38d8-4abe-bb0a-a2dd309ed0fc.png)

Thank you!
Natalie

**Comment by kiadso** [comment]
I will pass along this request- thank you for submitting it, Natalie!

I know it's an extra step, but an interim solution, and the way I have been doing it, is running a script on the Flag Export that gives me the data the way we need it every time I upload another data set. (It helps also with tracking which flags were there last run as compared to the most recent run.)

Either way, I'll pass this on and see if your request would be feasible.

**Comment by kiadso** [comment]
Hi, the AHAR team has discussed this and we think that collapsing those rows across the board would cause issues for CoCs because, especially for Warning flags, they may have different reasons for a given flag that varies from Project to Project and they need the ability to add comments in a more granular way. 
We do have on our drawing board for next year to add some metrics for flag counts and other ways of aggregating the flag data to help CoCs and vendors with planning. Until we can have that, please feel free to use the Export Flag file to create the metrics helpful to you. Thanks again for the question, Natalie!
