### ISSUE TITLE
Flag 684-1 (counting Ethnicity)

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#868]
Hi @kiadso ,

My upload: https://testing.hudhdx2.info/dataset/1325/warning

According to LSA spec and sample code, we should use `Race = 5 and Ethnicity <> 1` condition for population = 56.
![image](https://user-images.githubusercontent.com/28144855/145047473-3ce88ab4-d06f-4be6-b731-a87e4601c8e6.png)
IMPORTANT: `Ethnicity <> 1` is not the same as `Ethnicity = 0`.

But validation system uses  `Ethnicity = 0` instead of `Ethnicity <> 1` and it causes Flag 684.
Could you please ask dev team to review and fix "SAS logic for the LSAPerson version" formula? Maybe `non-Hispanic/Latin(a)(o)(x)` also should be rewritten, i.e. as `other than Hispanic/Latin(a)(o)(x)`?
![image](https://user-images.githubusercontent.com/28144855/145046953-6f7b5bcb-9ce3-478b-a74c-484cbd906657.png)

![image](https://user-images.githubusercontent.com/28144855/145048307-fadd4ac1-bd92-4302-b05a-a045d8b22657.png)

Please notice that other flags may have `Ethnicity == 0` SAS logic and they should be reviewed and fixed if needed.

Best regards,
Natalie

**Comment by kiadso** [comment]
Thank you so much Natalie! (Escalated)

**Comment by kiadso** [comment]
Natalie could you upload again? Your last upload was just minutes prior to the last push to Test. :) If you're seeing it's fixed, feel free to close this.

Thank you-
Genelle

**Comment by nataliesus** [comment]
Hi Genelle!

The issue is still there (https://testing.hudhdx2.info/dataset/1370/warning): 
![image](https://user-images.githubusercontent.com/28144855/146007558-0ba8e2ad-f30c-4ac4-9cc2-3dccf4f50a53.png)

Instead of `Ethnicity==0` it should be `Ethnicity!=0` in the flag calculation.

Could you please take a look?

Thank you!
Natalie

**Comment by OksanaSukhorukova** [comment]
Hi @kiadso , the flag was updated but looks like that the issue is still here, instead of Population 56 flag reports Population 65
![image](https://user-images.githubusercontent.com/71442061/146165465-cfaaecf1-3693-4793-a25f-385579b88a03.png)
According to spec for Population=65 we need to use condition Ethnicity = 0
Ethnicity != 1 is not equal Ethnicity = 0, because possible values for Ethnicity are -1,0,1,98,99
Could you please take a look?

**Comment by kiadso** [comment]
I have sent this ticket back to Dev, thank you for your patience!

**Comment by TanyaPieterse** [comment]
Good morning,
We have the same Flag.  
Because ActiveAge in tlsa_Enrollment could not be calculated, HoHAdult.stat is then set to 0.  And because HoHAdult.stat = 0, the Ethnicity is set to -1 in tlsa_Person (Step'5.3/5.4').  Therefore tlsa_Person has additional values like -1 for Ethnicity.  I agree lsaPerson should be counted as Ethnicity=0 instead of Ethnicity<>1.
Thanks!

**Comment by kiadso** [comment]
This fix has been pushed to production. Please respond here if you are still seeing these flags or let me know what CoC(s) I should check that uploaded after noon today. (I'm in EST)
