### ISSUE TITLE
Flags 29-44 (roughly)

### ISSUE THREAD

**Issue by kiadso** [MollyMcEvilley/LSASampleCode#886]
Hi Molly!

We recently turned on several flags that were accidentally off before, and they are flagging on the PCL dataset on Test. These flags are all referring to the yyyymmdd hhmmss date columns. In researching it, I found that the HMIS CSV has no quotes around the dates in these columns, but the LSA export does have quotes around the dates in those columns. 

I didn’t notice anything in the HMIS CSV Export specs or in the LSA specs about quoting any columns of a date type other than "string". This may or may not be why they’re flagging, and Jenna is looking into other reasons, but I wanted to ask if this is something that needs to be addressed in the sample code? I'm setting it to Sample Code for now, but we are looking for other reasons these flags are throwing also! Thanks!

**Comment by nataliesus** [comment]
Hi Genelle!

Isn't is flag issue that a date field that is generated without quotes is reported as a flag issue? It doesn't contain comma so it is completely valid from CSV formatting view.

![image](https://user-images.githubusercontent.com/28144855/145992840-ee7faa2f-6673-4465-a14e-2a9ca86ec4cd.png)

Best regards,
Natalie

**Comment by kiadso** [comment]
Hi Natalie,

This group of flags is being explored on both sides, as a possible flag issue and a possible sample code issue. The thing I'm curious about is why the CSV sample data does not have quoted dates and the LSA sample data does. It may not matter at all, just want to figure out why. 
Are your LSA date columns quoted in the CSV when you open it in Notepad?

**Comment by nataliesus** [comment]
Hi Genelle,

I cannot say about other vendors, but we do not have quotes around date columns in **our** LSA implementation (for Bitfocus):
![image](https://user-images.githubusercontent.com/28144855/145995869-426bb7df-5f34-4835-b9b4-1563d81443f3.png)

----

LSA sample report does have quotes
![image](https://user-images.githubusercontent.com/28144855/145996571-a44f9be5-fa0e-4166-8405-f7fec0e4ac36.png)
but most of them are redundant, because quotes are needed only if column is a string and contains comma inside the column text. For all other cases it just increases the file size and does not impact on anything.

Best regards,
Natalie

**Comment by kiadso** [comment]
Thank you for checking Natalie. I'm seeing that it's flagging in your dataset so it seems like the quotes question is irrelevant. I'm going to leave this open since it is still an issue that Dev is working on.

**Comment by kiadso** [comment]
These flags have been turned off until we can work out the issue.

**Comment by kiadso** [comment]
Hi, this issue has been resolved, please let us know if you are still seeing date formatting flags!
