### ISSUE TITLE
Flag 448-1

### ISSUE THREAD

**Issue by eanders** [MollyMcEvilley/LSASampleCode#897]
We're seeing one CoC with flag 448-1 
> The LSAHousehold field HHChronic must be consistent with the information provided by the project-specific versions of HHChronic (ESTChronic, RRHChronic, and PSHChronic). If HHChronic equals 1 (chronically homeless), then at least one of the project-specific versions must equal 1. If HHChronic equals 0 (no), then all of the project-specific versions must equal 0. The following row in your LSAHousehold file violates this rule.

I'm really not sure where to begin on tracking this down, it looks like maybe `hhchronic` is 0 and `rrhchronic` is 1.  Does anyone have a sense of what data situation could possibly trigger this?  Someone on the LSA call suggested it might be a sample code versions mis-match (thanks for the suggestion!) but it turns out we're up-to-date.  If anyone has thoughts on where to begin, I'd be very appreciative.

**Comment by kiadso** [comment]
Hi Elliott,

What is the CoC experiencing this?

Thanks

**Comment by eanders** [comment]
@kiadso PA-600.  Thanks!

**Comment by jbloescw** [comment]
@eanders Can you check your section 6.1?  I know you say you are up to date and I thought the same thing but this never showed up in the change history.  It was just MAX(HHChronic) and I noticed that it is actually a case when statement to set it.
This flag originally triggered for us when a couple clients were in different enrollments/households.  Each enrollment the client had different answers that made one chronic and the other one not.  Since both were active for the reporting period it was causing HHChronic to be a 2 but program specific had a 1.  
It's odd that a client would have 2 differing answers in such a close timeframe but once I caught that setting for HHChronic in 6.1, it cleared it up.
Worth double checking I suppose.

**Comment by eanders** [comment]
@jbloescw , thanks for the info.  Yep, our code matches this exactly:
https://github.com/HMIS/LSASampleCode/blob/d23bf4db658dec21e1e3434b50a5d154bbfd4f2f/06%20LSAHousehold.sql#L9-L29
Should line 16 be `max(hhid.HHChronic)`?  What you say about someone getting counted in multiple times makes perfect sense.  I'll see if I can track down the who from the intermediate tables.

**Comment by jbloescw** [comment]
@eanders Your line 16 looks good.  I have no idea why we had a MAX(hhid.HHChronic) on that line.

**Comment by kiadso** [comment]
An LSA liaison has reached out to the CoC in question and we expect to reach resolution that way. If you feel this is a problem with the flag itself, please feel free to re-open. Thanks!

**Comment by eanders** [comment]
@kiadso can you also have the liaison reach out to MA-500?

**Comment by kiadso** [comment]
Someone should be contacting them if they have not already! @eanders

**Comment by eanders** [comment]
Thank you!
