### ISSUE TITLE
Flag 1241 Overall and Sub Project Population Count not Aligning

### ISSUE THREAD

**Issue by eccovia-csmith** [MollyMcEvilley/LSASampleCode#908]
This is referencing Flag 1241 and all sub flags under it. The premise of the flag is that the summed values for projects within a project type for a population is greater than the total count for the project type for a population.

In section 8.3 & 8.4 this data is aggregated by ProjectID or NULL (NULL being overall count). The DISTINCT on PersonalID makes it so that when grouping by ProjectIDs, an individual can be counted for each unique project they are enrolled in. Although when grouping for overall, they will only be counted once as they are grouped by NULL and there is a DISTINCT on PersonalID. This results in Flag 1241 and some other similar flags saying that the sub-population count results are higher than the overall project type population count. This is due to Persons having multiple enrollments within the report range but are only getting counted once in the overall count.

There may need to be a concatenation on Unique PersonalID and ProjectID but during my own research I find that it may end up producing incorrect counts based on the current specifications. So either the flag needs to be correct to account for this, or the SQL & Specs need to be corrected to properly count these individuals with multiple enrollments

https://github.com/HMIS/LSASampleCode/blob/93b94cd9feb0fd6d3e4d224b5908450e8167a642/09%20LSACalculated%20AHAR%20Counts.sql#L267

**Comment by kiadso** [comment]
Hi Eccovia,
This flag was reclassified as a Warning because it was being thrown due to clients aging from one Household Type to another during the reporting period. This and other similar flags were reported as GitHub Issue #892. You can check the list of flags that are/were under review here: https://hudhdx2infoissues.weebly.com/.
They are marked as Vendor Warnings because there may be instances where these are vendor issues and we cannot classify separate sub-flags differently this year.
We're recommending that vendors focus on Vendor Errors ahead of Vendor Warnings. Your vendor flag data is emailed every Tuesday.
Thanks
