### ISSUE TITLE
Section 11.6: distinct usage in Sample Code

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#937]
Hi @MollyMcEvilley,

Could you please remove "distinct" from [SSNNotProvided] and [SSNMissingOrInvalid] calculation select statement in Sample Code? No need to update Spec.

![image](https://user-images.githubusercontent.com/28144855/183525347-2d3aa5e5-ab93-4a13-9112-638688e4037d.png)

Thank you,
Natalie

**Comment by MollyMcEvilley** [comment]
The use of DISTINCT in the data quality counts was also raised in issues #933 and #940....  For now, I'm going to use this issue to consolidate conversation / questions / issues related to DISTINCT as it is used anywhere in the sample code...

Question:  Are you seeing any actual overhead to specifying DISTINCT?  I'm asking because I wholeheartedly acknowledge that I liberally sprinkle DISTINCT in my code without consideration of the overhead pretty much whenever I need a distinct count regardless of whether or not the query would produce a distinct count without it... I have no objection to reviewing all of the sample code to remove it where there's cost and no benefit...  BUT I'm seeing exactly the same execution plan and query cost regardless. 

![image](https://user-images.githubusercontent.com/6156815/185200677-230c5d98-f81a-4bea-8e4c-e134bdbda788.png)

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

I just thought using distinct wasn't necessary if there are no duplicates by selected statements. You can keep it.
