### ISSUE TITLE
Section 11.6: [DistinctSSNValueNotUnique] question

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#938]
Hi @MollyMcEvilley ,

![image](https://user-images.githubusercontent.com/28144855/183526175-cb7fa49a-f9cc-4dad-ab4c-a4da8ed5b9c5.png)

Test scenario:
- Client A: SSN = 123-12-1230, SSNDataQuality = 1, SSNValid = 1
- Client B: SSN = 123-12-1230, SSNDataQuality = 8, SSNValid = 9

**Question 1:**
in one sentence it is said that [DistinctSSNValueNotUnique] is "A count of **distinct** hmis_Client.**SSN** values". So for our test scenario [DistinctSSNValueNotUnique] = **1**.
In the next sentence, it is said that it is "the number of **duplicate clients**". So for our test scenario [DistinctSSNValueNotUnique] = **2**.
Which of the results - 1 or 2 - is correct? Could you please update Spec?

**Question 2:**
Could you please clarify what "SSNValid = 1" means in the spec (highlighted on the screenshot)? Should we check for duplicate ssn only within clients who have SSNValid = 1? Or at least one of these clients must have SSNValid = 1 and the rest of the clients with the same ssn may have SSNValid = 0? For our scenario, should Client A and Client B be counted as duplicates if they have different SSNValid values?

Could you please review the sample code after Spec is corrected?

Thank you,
Natalie

**Comment by MollyMcEvilley** [comment]
Updated the specs to clarify that as long as at least one of the records in tlsa_Person has **SSNValid** = 1, the duplicates should be counted both in **ClientSSNNotUnique** and **DistinctSSNValueNotUnique**.

I also updated the sample code because although it was doing that part correctly, an inner join to the subquery was leaving the values NULL instead of setting them to zero when there were no dupes.
