### ISSUE TITLE
Section 11.7: [MonthsHomeless] sample code issue

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#942]
Hi @MollyMcEvilley,

Could you please take a look if sample code should be fixed?

![image](https://user-images.githubusercontent.com/28144855/183532725-02947b3c-d029-4671-8b11-7035aeb29bdc.png)

Best regards,
Natalie

**Comment by nataliesus** [comment]
btw, this year formula to calculate [MonthsHomeless] is completely different than prev years. Some scenarios were completely removed. Was it done intentionally?

**Comment by MollyMcEvilley** [comment]
The bug was a copy/paste issue -- I copied the code from **TimesHomeless** and although I did correct the field name in the code to _MonthsHomelessPastThreeYears_, I failed to update to the appropriate values for that field. Commit forthcoming...

There was an intentional simplification of the logic here.  In past years, instead of just looking at _PreviousStreetESSH_, we also looked at _LengthOfStay_, with or without _LivingSituation_.  However, the only time a value of 1 for _PreviousStreetESSH_ is possible or relevant, the conditions related to those fields are already (theoretically) met -- so specifying them is not necessary.  

![image](https://user-images.githubusercontent.com/6156815/185180874-0fd273e8-e670-4b0d-96e1-77ab864a3b42.png)
