### ISSUE TITLE
[HomelessDate] difference between FY2021 and FY2022

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#945]
Hi @MollyMcEvilley ,

Could you please compare calculations for FY2021 and FY2022 because there are significant changes:
1. [LivingSituation] = 27 was removed in FY2022. Was it done on purpose?
2. [or Condition 3] and [or Condition 4] were removed in  FY2022. Was it done on purpose?

![image](https://user-images.githubusercontent.com/28144855/184458217-800f620f-12eb-42f4-95a9-faa51ee9e8cc.png)

If anything should be updated in LSA FY2022, could you please also compare and add missing code for:
- TimesHomeless
- MonthsHomeless 

Thank you!
Natalie

**Comment by nataliesus** [comment]
also, could you please update spec specifying from which table [EntryDate] column should be used: tlsa_Enrollment or hmis_Enrollment?
![image](https://user-images.githubusercontent.com/28144855/184494022-bb32af49-8e5c-4d7f-9e6e-15bfec8960a7.png)

**Comment by MollyMcEvilley** [comment]
1. Yes, this was done on purpose — 27 is not a valid value for FY22.

2. This was an intentional streamlining/simplification of the logic. A value of one in _DateToStreetESSH_ is only relevant or valid if the conditions related to _LengthOfStay_/_LivingSituation_ in scenarios three and four are met.

3. The italics (should!) always mean the hmis_ tables.
