### ISSUE TITLE
LSA CSV Export Temp Tables: SSNValid discrepancies for tlsaPerson

### ISSUE THREAD

**Issue by evaripatis** [MollyMcEvilley/LSASampleCode#959]
In the provided tlsa_Person.csv file, 552 out of the 561 records have an SSValid value of 0, which is matched by an SSNMissingOrInvalid value of 552 in the LSAReport.csv file.  However, when the LSA HMIS CSV Export files are run against the sample SQL scripts, the SSNMissingOrInvalid value drops to 96.  This discrepancy is also reflected with the generated tlsa_Person.csv file, which then has 456 individuals with an SSValid value of 1 and 96 individuals with a value of 0.  My assumption is that the provided tlsa_Person.csv and LSAReport.csv files are incorrect for these numbers.  Can you confirm?

**Comment by evaripatis** [comment]
There was no comment added to this ticket, nor was there any apparent change to either the LSAReport.csv or tlsa_Person.csv files.  I'm unclear on what was done to result in this ticket being closed out.

**Comment by MollyMcEvilley** [comment]
Thank you for following up on this,  As it turns out, for reasons that are entirely my fault, the SSN values in my database were different from the ones in the HMIS CSV files.  I had added a line of code to my import process to change them while I was testing the SSNValid, so no matter how many times i re-imported and re-ran the code, the SSNValid results were consistent with the records in my hmis_Client file.  Commit forthcoming of new test kit files.
