### ISSUE TITLE
LSA CSV Export Temp Tables.zip: tlsa_Enrollment.csv - LastBednight date format 

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#972]
Hi @MollyMcEvilley ,

Could you please take a look at date format for [LastBednight] column in tlsa_Enrollment.csv file in LSA CSV Export Temp Tables.zip?
![image](https://user-images.githubusercontent.com/28144855/194784625-e99ca247-1fbf-4639-83e7-3175faeff31d.png)

It looks like it is mm/dd/yyyy. Could you please re-genarate zip archive with [LastBednight] using the format other date columns (EntryDate,MoveInDate,ExitDate) we generated?

Thank you!
Natalie

**Comment by kcourtneywellsky** [comment]
We noticed the same problem with the incorrect date format on LastBedNight in tlsa_Enrollment.csv, as well as StartDate and EndDate in sys_TimePadded.csv. This is likely caused by editing the files in a program such as Excel with the column's date format set to "mm/dd/yyyy". It would definitely make it easier for us to compare results with the expected output if the date formats are all set to the "YYYY-MM-DD" format.
